language: java
env:
  - TEST_DIR=Viikko4
  - TEST_DIR2=LoginWeb2  
script: cd $TEST_DIR/LoginWeb2  
  - mvn test
  - mvn integration-test
after_success:
  - mvn clean cobertura:cobertura coveralls:report
